export const KENYAN_UNIVERSITIES = [
    "University of Nairobi (UoN)",
    "Kenyatta University (KU)",
    "Moi University",
    "Egerton University",
    "Jomo Kenyatta University of Agriculture and Technology (JKUAT)",
    "Maseno University",
    "Masinde Muliro University of Science and Technology (MMUST)",
    "Technical University of Kenya (TUK)",
    "Technical University of Mombasa (TUM)",
    "Dedan Kimathi University of Technology (DeKUT)",
    "Chuka University",
    "Kabianga University",
    "Kisii University",
    "Karatina University",
    "Meru University of Science and Technology",
    "Multimedia University of Kenya",
    "Pwani University",
    "South Eastern Kenya University (SEKU)",
    "Taita Taveta University",
    "University of Eldoret",
    "Kibabii University",
    "Garissa University",
    "Rongo University",
    "Co-operative University of Kenya",
    "Machakos University",
    "Murang'a University of Technology",
    "University of Embu",
    "Turkana University College",
    "Bomet University College",
    "Tharaka University College",
    "Alupe University College",
    "Tom Mboya University College",
    "Kaimosi Friends University College",
    "Strathmore University",
    "United States International University Africa (USIU-Africa)",
    "Catholic University of Eastern Africa (CUEA)",
    "Mount Kenya University (MKU)",
    "Daystar University",
    "Africa Nazarene University",
    "Kabarak University",
    "KCA University",
    "Pan Africa Christian University",
    "Kenya Methodist University (KeMU)",
    "St. Paul's University",
    "Great Lakes University of Kisumu",
    "Zetech University",
    "Riara University",
    "Amref International University",
    "Pioneer International University",
    "Umma University",
    "International Leadership University",
    "Lukenya University",
    "Management University of Africa",
    "Presbyterian University of East Africa",
    "Other"
];
