"""added profile id to entities

Revision ID: 0cb69ea28638
Revises: 32c5908b64de
Create Date: 2026-01-20 07:31:34.893674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb69ea28638'
down_revision: Union[str, Sequence[str], None] = '32c5908b64de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('profile_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_entities_profile_id'), 'entities', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'entities', 'profiles', ['profile_id'], ['id'], ondelete='SET NULL')
    op.add_column('profiles', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_default')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_index(op.f('ix_entities_profile_id'), table_name='entities')
    op.drop_column('entities', 'profile_id')
    # ### end Alembic commands ###
