"""rename publications column

Revision ID: 15183a645a6e
Revises: 692e79a1540f
Create Date: 2025-10-07 19:29:44.696643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15183a645a6e'
down_revision: Union[str, Sequence[str], None] = '692e79a1540f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('publications_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('entities', 'publications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('publications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('entities', 'publications_meta')
    # ### end Alembic commands ###
