"""adding lat and log to partners

Revision ID: 620b65b62549
Revises: 7fe6839183b9
Create Date: 2026-01-31 15:37:16.654198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620b65b62549'
down_revision: Union[str, Sequence[str], None] = '7fe6839183b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('partners', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'longitude')
    op.drop_column('partners', 'latitude')
    # ### end Alembic commands ###
