"""UI V4 database

Revision ID: 7e518bc7ce34
Revises: 
Create Date: 2025-10-07 13:29:04.680770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e518bc7ce34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('entities', sa.Column('climate_tech_focus', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entities', sa.Column('climate_impact_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entities', sa.Column('tsv_document', postgresql.TSVECTOR(), nullable=True))
    op.drop_column('entities', 'publications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('publications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('entities', 'tsv_document')
    op.drop_column('entities', 'climate_impact_metrics')
    op.drop_column('entities', 'climate_tech_focus')
    op.drop_column('entities', 'entity_type')
    # ### end Alembic commands ###
