"""included profile image in Profile

Revision ID: 7f214ae2e7cc
Revises: b5293b0616db
Create Date: 2025-10-08 22:02:34.171128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f214ae2e7cc'
down_revision: Union[str, Sequence[str], None] = 'b5293b0616db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'profile_image')
    # ### end Alembic commands ###
