"""add event_registrations table

Revision ID: abc123def456
Revises: fee3eb6e27ff
Create Date: 2026-01-18 06:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from typing import Union

# revision identifiers, used by Alembic.
revision = 'abc123def456'
down_revision = 'a38a004dbd6e'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_registrations',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('event_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('profile_id', sa.UUID(as_uuid=True), nullable=True),
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('position', sa.String(length=255), nullable=True),
        sa.Column('organization', sa.String(length=255), nullable=True),
        sa.Column('participation_type', sa.String(length=50), nullable=False),
        sa.Column('attendance_type', sa.String(length=50), nullable=False),
        sa.Column('ticket_type', sa.String(length=50), nullable=True),
        sa.Column('wants_profile_visible', sa.Boolean(), nullable=False),
        sa.Column('profile_visibility_types', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('registration_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('create_account', sa.Boolean(), nullable=False),
        sa.Column('metadata_', postgresql.JSONB(), nullable=True),
        sa.Column('special_requirements', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_registrations_event_id'), 'event_registrations', ['event_id'])
    op.create_index(op.f('ix_event_registrations_profile_id'), 'event_registrations', ['profile_id'])
    op.create_index(op.f('ix_event_registrations_email'), 'event_registrations', ['email'])
    op.create_index(op.f('ix_event_registrations_registration_date'), 'event_registrations', ['registration_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_registrations_registration_date'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_email'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_profile_id'), table_name='event_registrations')
    op.drop_table('event_registrations')
    # ### end Alembic commands ###
