"""added timestamp mixin

Revision ID: ac96364199ce
Revises: 86d9c153e0ec
Create Date: 2025-10-21 13:49:14.499657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'ac96364199ce'
down_revision: Union[str, Sequence[str], None] = '86d9c153e0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema safely for timestamp mixin columns."""

    conn = op.get_bind()
    inspector = inspect(conn)

    tables = [
        "ecosystem_entity_links",
        "entities",
        "entity_embeddings",
        "entity_images",
        "funders",
        "match_records",
        "message_attachments",
        "messages",
        "notifications",
        "profile_backlinks",
        "profiles",
        "proposals",
        "publications",
        "queries",
        "session_entities",
        "sessions",
        "shared_sessions",
        "user_entity_links",
        "users",
        "verifications",
    ]

    for table in tables:
        existing_cols = {col["name"] for col in inspector.get_columns(table)}

        # Only add columns that don't already exist
        if "created_at" not in existing_cols:
            op.add_column(
                table,
                sa.Column(
                    "created_at",
                    sa.DateTime(timezone=True),
                    server_default=sa.text("now()"),
                    nullable=False,
                ),
            )

        if "updated_at" not in existing_cols:
            op.add_column(
                table,
                sa.Column(
                    "updated_at",
                    sa.DateTime(timezone=True),
                    server_default=sa.text("now()"),
                    nullable=False,
                ),
            )

        if "deleted_at" not in existing_cols:
            op.add_column(
                table,
                sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
            )


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'deleted_at')
    op.drop_column('verifications', 'updated_at')
    op.drop_column('verifications', 'created_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('user_entity_links', 'deleted_at')
    op.drop_column('user_entity_links', 'updated_at')
    op.drop_column('user_entity_links', 'created_at')
    op.drop_column('shared_sessions', 'deleted_at')
    op.drop_column('shared_sessions', 'updated_at')
    op.drop_column('sessions', 'deleted_at')
    op.drop_column('sessions', 'updated_at')
    op.drop_column('sessions', 'created_at')
    op.drop_column('session_entities', 'deleted_at')
    op.drop_column('session_entities', 'updated_at')
    op.drop_column('session_entities', 'created_at')
    op.drop_column('queries', 'deleted_at')
    op.drop_column('queries', 'updated_at')
    op.drop_column('queries', 'created_at')
    op.drop_column('publications', 'deleted_at')
    op.drop_column('publications', 'updated_at')
    op.drop_column('proposals', 'deleted_at')
    op.drop_column('proposals', 'updated_at')
    op.drop_column('profiles', 'deleted_at')
    op.drop_column('profiles', 'updated_at')
    op.drop_column('profile_backlinks', 'deleted_at')
    op.drop_column('profile_backlinks', 'updated_at')
    op.drop_column('notifications', 'deleted_at')
    op.drop_column('notifications', 'updated_at')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'updated_at')
    op.drop_column('message_attachments', 'deleted_at')
    op.drop_column('message_attachments', 'updated_at')
    op.drop_column('match_records', 'deleted_at')
    op.drop_column('match_records', 'updated_at')
    op.drop_column('funders', 'deleted_at')
    op.drop_column('funders', 'updated_at')
    op.drop_column('entity_images', 'deleted_at')
    op.drop_column('entity_images', 'updated_at')
    op.drop_column('entity_embeddings', 'deleted_at')
    op.drop_column('entity_embeddings', 'updated_at')
    op.drop_column('entities', 'deleted_at')
    op.drop_column('entities', 'updated_at')
    op.drop_column('entities', 'created_at')
    op.drop_column('ecosystem_entity_links', 'deleted_at')
    op.drop_column('ecosystem_entity_links', 'updated_at')
    # ### end Alembic commands ###
