"""add_partner_tables

Revision ID: bbf52a549e23
Revises: ca60f9c9e771
Create Date: 2026-01-30 21:56:56.172121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbf52a549e23'
down_revision: Union[str, Sequence[str], None] = 'ca60f9c9e771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('sector_focus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_name'), 'partners', ['name'], unique=False)
    op.create_index(op.f('ix_partners_slug'), 'partners', ['slug'], unique=True)
    op.create_index(op.f('ix_partners_user_id'), 'partners', ['user_id'], unique=False)
    op.create_table('partner_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_invitations_partner_id'), 'partner_invitations', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_invitations_token'), 'partner_invitations', ['token'], unique=True)
    op.create_table('partner_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_members_partner_id'), 'partner_members', ['partner_id'], unique=False)
    op.create_index('ix_partner_members_unique', 'partner_members', ['partner_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_partner_members_user_id'), 'partner_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_members_user_id'), table_name='partner_members')
    op.drop_index('ix_partner_members_unique', table_name='partner_members')
    op.drop_index(op.f('ix_partner_members_partner_id'), table_name='partner_members')
    op.drop_table('partner_members')
    op.drop_index(op.f('ix_partner_invitations_token'), table_name='partner_invitations')
    op.drop_index(op.f('ix_partner_invitations_partner_id'), table_name='partner_invitations')
    op.drop_table('partner_invitations')
    op.drop_index(op.f('ix_partners_user_id'), table_name='partners')
    op.drop_index(op.f('ix_partners_slug'), table_name='partners')
    op.drop_index(op.f('ix_partners_name'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
