"""added embeddings to funder

Revision ID: c4f4c3032ec5
Revises: 7f214ae2e7cc
Create Date: 2025-10-14 12:41:08.212813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4f4c3032ec5'
down_revision: Union[str, Sequence[str], None] = '7f214ae2e7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funders', sa.Column('embeddings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funders', 'embeddings')
    # ### end Alembic commands ###
