"""included bulk csv import schema

Revision ID: ca60f9c9e771
Revises: e8887f1df15f
Create Date: 2026-01-24 07:20:36.333394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca60f9c9e771'
down_revision: Union[str, Sequence[str], None] = 'e8887f1df15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_registrations', 'password_setup_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('event_registrations', 'rejection_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('import_batches', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_profiles_invitation_status'), table_name='profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_profiles_invitation_status'), 'profiles', ['invitation_status'], unique=False)
    op.drop_column('import_batches', 'deleted_at')
    op.alter_column('event_registrations', 'rejection_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('event_registrations', 'password_setup_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
