"""edited event schema

Revision ID: d31bde729044
Revises: 461953dedbeb
Create Date: 2026-02-06 03:35:32.890541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd31bde729044'
down_revision: Union[str, Sequence[str], None] = '461953dedbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('virtual_link_description', sa.String(length=200), nullable=True))
    op.add_column('events', sa.Column('additional_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'additional_links')
    op.drop_column('events', 'virtual_link_description')
    # ### end Alembic commands ###
