"""included hackathon tables

Revision ID: d941951b59a4
Revises: a1b2c3d4e5f6
Create Date: 2026-02-01 06:29:21.040610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd941951b59a4'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('hackathon_configs_event_id_key'), 'hackathon_configs', type_='unique')
    op.drop_index(op.f('ix_hackathon_configs_event_id'), table_name='hackathon_configs')
    op.create_index(op.f('ix_hackathon_configs_event_id'), 'hackathon_configs', ['event_id'], unique=True)
    op.add_column('partners', sa.Column('is_hackathon', sa.Boolean(), server_default='false', nullable=True))
    op.drop_constraint(op.f('scoring_schemas_hackathon_id_key'), 'scoring_schemas', type_='unique')
    op.drop_index(op.f('ix_scoring_schemas_hackathon_id'), table_name='scoring_schemas')
    op.create_index(op.f('ix_scoring_schemas_hackathon_id'), 'scoring_schemas', ['hackathon_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_schemas_hackathon_id'), table_name='scoring_schemas')
    op.create_index(op.f('ix_scoring_schemas_hackathon_id'), 'scoring_schemas', ['hackathon_id'], unique=False)
    op.create_unique_constraint(op.f('scoring_schemas_hackathon_id_key'), 'scoring_schemas', ['hackathon_id'])
    op.drop_column('partners', 'is_hackathon')
    op.drop_index(op.f('ix_hackathon_configs_event_id'), table_name='hackathon_configs')
    op.create_index(op.f('ix_hackathon_configs_event_id'), 'hackathon_configs', ['event_id'], unique=False)
    op.create_unique_constraint(op.f('hackathon_configs_event_id_key'), 'hackathon_configs', ['event_id'])
    # ### end Alembic commands ###
