"""add like_count to entities

Revision ID: e8ceca8b5450
Revises: 2e4b3d6b83bf
Create Date: 2026-01-31 11:32:11.371200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ceca8b5450'
down_revision: Union[str, Sequence[str], None] = '2e4b3d6b83bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('like_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('entities', sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('entities', sa.Column('share_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('entities', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('notifications', sa.Column('actor_user_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('group_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_notifications_actor_user_id'), 'notifications', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_group_key'), 'notifications', ['group_key'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('partners', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('partners', sa.Column('featured_at', sa.DateTime(), nullable=True))
    op.add_column('partners', sa.Column('organization_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('suspended_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('suspension_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'suspension_reason')
    op.drop_column('users', 'suspended_at')
    op.drop_column('users', 'is_suspended')
    op.drop_column('partners', 'organization_type')
    op.drop_column('partners', 'featured_at')
    op.drop_column('partners', 'is_featured')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_group_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_actor_user_id'), table_name='notifications')
    op.drop_column('notifications', 'group_key')
    op.drop_column('notifications', 'actor_user_id')
    op.drop_column('entities', 'view_count')
    op.drop_column('entities', 'share_count')
    op.drop_column('entities', 'comment_count')
    op.drop_column('entities', 'like_count')
    # ### end Alembic commands ###
