"""added is_admin to the user table

Revision ID: fee3eb6e27ff
Revises: 4ac7cb425cfa
Create Date: 2026-01-10 17:46:21.392836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee3eb6e27ff'
down_revision: Union[str, Sequence[str], None] = '4ac7cb425cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
#     # ### end Alembic commands ###

def upgrade() -> None:
    """Upgrade schema."""
    # Add the column with server_default=False so existing rows get FALSE
    op.add_column(
        'users',
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # Optional: remove server default if you don't want future inserts to automatically get FALSE
    op.alter_column('users', 'is_admin', server_default=None)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
