import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuththLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log("children:", children)
  return <div className="bg-background text-foreground">{children}</div>;
}
